version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo_dev
    ports:
      - "27017:27017"
    volumes:
      - ./public/data:/data/db
    environment:
      MONGO_INITDB_DATABASE: f1
    restart: unless-stopped